paths:
  raw_dir: data/raw # внутри train.parquet, benchmark_queries.parquet, benchmark_items.parquet
  processed_dir: data/processed # результаты предобработки и валидации
  artifacts_dir: artifacts # эмбеддинги
  output: answer.csv

seed: 42 #случайный сид
device: auto # auto, cuda, cpu

preprocess:
  desc_max_words: 100 # длинное описание мешает BM25 (из-за мусора в конце : "звоните", "работаем без выходных" и тд), средняя длина описания в train ~140
  max_address_words: 12 

validation:
  # кол-во вхождений из обучающей выборки, которое используем для проверки полноты готовой модели
  n_queries: 5000

# параметры алгоритма ранжирования bm25
bm25:
  k1: 1.2 # чем k1 ниже, тем меньше повторные вхождения слова увеличивают интерес к объявлению
  b: 0.75  # чем выше, тем сильнее штрафуются длинные описания
  alpha_location: 4.0 # множитель дающий бонус местным объявлениям 
  beta_vid: 1.0 # множитель дающий бонус, если вид услуги совпадает с заданным фильтром

# локация - важнейший критерий поиска. но определить локацию запроса мы можем только косвенно (если люди из локации 637640 выбирают объявления, которые в основном лежат вокруг точки (55.75, 37.62), то локация, скорее всего, Москва, и её центр где-то там же)
location:
  min_share: 0.01 # локация объявления считается "своей", если на неё приходится хотя бы min_share*100% выборов в train
  radius_km: 50 # к "своей" локации прибавляем всё в радиусе radius_km от центра локации поиска
# TODO : переработать поиск локации, текущая реализация не подходит для точных рекомендаций в редких локациях (по которым мало объявлений)

# в train более 99% всех вхождений имеют категорию 114 (скорее всего это "услуги"), но в benchmark только 91% ищут категорию 114, остальные ищут в категории 0 (очень редко в какой-то определенной категории)
# получается, мы вообще не можем использовать категорию, как важный критерий поиска, но при этом мы не можем её выкинуть. поэтому штрафуем все объявления вне категории 114, чтобы они попадались в топ 50 только при огромном совпадении с запросом
non_service:
  penalize: true # если false, то штрафы не происходят вообще и все объявления считаются равными
  bm25_factor: 0.1
  emb_penalty: 1.0

# гиперпараметры эмбеддинга
embeddings:
  max_len: 128 # сколько токенов текста мы учитываем 
  desc_words: 40 # кол-во слов из описания попадающих в модель (эмбеддинг игнорирует desc_max_words)
  batch_size: 64 # если видеокарте не хватает видеопамяти - уменьшить
  models:
    - key: e5-base-ft # имя модели внутри проекта
      path: artifacts/models/e5-base-ft # путь (локальный или Hugging Face)
      
      # две важные метки для моделей e5 (не трогать)
      q_prefix: "query: " 
      d_prefix: "passage: "

      # эти две метрики при смене модели нужно тюнить
      gamma: 0.3 # бонус к сходству местным объявлениям
      delta: 0.2 # бонус при совпадении вида услуги

      weight: 0.6 # вес в RRF (вес модели при объединении с bm25)

# reciprocal rank fusion - алгоритм, с помощью которого объединим списки, полученные от bm25 и эмбеддинга
fusion:
  bm25_weight: 0.4 # вес bm25, меньше 0.4 делать не стоит (был плохой результат)
  rrf_k: 60 # разница между местами
  depth: 1000 # сколько кандидатов каждого метода участвует в объединении

# дообучение
finetune:
  base_model: intfloat/multilingual-e5-base #модель
  output: artifacts/models/e5-base-ft 
  train_on: train_part # train_part - train и val не смешиваются; full - в обучении используется весь train (стоит использовать для тренировки итоговой модели)
  max_per_text: 20
  max_pairs: 200000
  batch_size: 64 # уменьшит, если у GPU не хватает памяти. большой батч здесь улучшит качество
  lr: 2.0e-5
  epochs: 1
  warmup_ratio: 0.1
